/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类: 
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "": "修炼之道放置",
    "| Total Earned:": "| 累计获得:",
    "Age:": "寿命:",
    "Auto Roll": "自动抽取",
    "Common": "普通",
    "COMMON": "普通",
    "Crit Damage": "暴击伤害",
    "Combat": "战斗",
    "Soul Shop": "灵魂商店",
    "Start Auto Roll": "开始自动抽取",
    "SWORD": "剑",
    "Sword": "剑",
    "Upgrade Cost:": "升级成本:",
    "Upgrade": "升级",
    "Unequip": "脱下",
    "UNCOMMON": "罕见",
    "Uncommon": "罕见",
    "Path of the Idle Cultivator": "修炼之道放置",
    "Monster HP": "怪物生命值",
    "Load Game": "加载游戏",
    "Legendary": "传说",
    "Join Discord": "加入 Discord",
    "Inventory": "库存",
    "Empty": "空",
    "Epic": "史诗",
    "EPIC": "史诗",
    "Current Rarity:": "当前稀有度:",
    "Damage": "伤害",
    "% (10 years to max)": "%（最多10年）",
    "Armor": "护甲",
    "Apply Tree": "应用树",
    "Active Techniques": "主动技能",
    "Available Points:": "可用点数:",
    "Automatically buy manuals until you get the desired rarity": "自动购买功法，直到你得到想要的稀有度",
    "Auto Roll Technique Manuals": "自动抽取技能功法",
    "Available Soul Power:": "可用灵力:",
    "Current Tier:": "当前层级:",
    "Current Action": "当前动作",
    "days remaining)": "天数剩余)",
    "Defense": "防御",
    "Delete Save": "删除存档",
    "Feet Armor": "脚甲",
    "Manuals": "功法",
    "Player Power Level": "玩家战力等级",
    "Power Level": "战力等级",
    "Qi": "气",
    "Progress:": "进度:",
    "QI Progress": "气进度",
    "QI Refining": "炼气",
    "QI/Day": "气/日",
    "RARE": "稀有",
    "Rare": "稀有",
    "Reach Bottleneck First": "先达到瓶颈",
    "Rebirth Info": "重生信息",
    "Rebirth Count": "重生次数",
    "Recommended Power Level:": "推荐战力等级:",
    "Refine Weapon": "精炼武器",
    "Stage": "阶段",
    "Skill Tree": "技能树",
    "Save Game": "保存游戏",
    "Spirit Stones": "灵石",
    "Spear Manual": "长矛功法",
    "SPEAR": "长矛",
    "Spear": "长矛",
    "Start Cultivating": "开始培养",
    "Start Combat": "开始战斗",
    "Start Practice": "开始练习",
    "Stats": "属性",
    "Start Refining": "开始精炼",
    "Actions": "动作",
    "Body Armor": "身体护甲",
    "Attempt Breakthrough": "尝试突破",
    "Ancient": "上古",
    "Breakthrough": "突破",
    "Buy Technique Manual": "购买技能功法",
    "Celestial": "天体",
    "Choose weapon type:": "选择武器类型:",
    "Clear Tree": "清除树",
    "Combat Status": "战斗状态",
    "Crit Chance": "暴击几率",
    "Cultivation Realm": "修炼境界",
    "Cultivation Manual": "修炼功法",
    "Current Soul Power": "当前灵力",
    "Head Armor": "头部护甲",
    "Cultivate": "修炼",
    "Fist Manual": "拳法",
    "Fist": "拳",
    "fist": "拳",
    "FIST": "拳",
    "Highest Monster": "最高的怪物",
    "Node Palette": "节点面板",
    "Pause": "暂停",
    "Player HP": "玩家生命值",
    "QI CONDENSATION": "凝气",
    "Sword Manual": "剑法",
    "Target Rarity:": "目标稀有度:",
    "Talk to Master": "与师父对话",
    "Talent": "天赋",
    "Refine Body": "炼体",
    "Redeem Code": "兑换码",
    "Weapons": "武器",
    "Toggle": "切换",
    "Total Soul Power": "总灵力",
    "Train Weapon": "训练武器",
    "Tree Builder": "树生成器",
    "Upgrade Manual": "升级功法",
    "Use QI and Spirit Stones to permanently increase your weapon's damage.": "使用气和灵石永久增加你的武器的伤害。",
    "Weapon Proficiencies": "武器熟练度",
    "Weapon Type:": "武器类型:",
    "Tier:": "层级:",
    "Refine your body to increase its rarity and power.": "精炼你的身体，可以提升它的稀有度和力量。",
    "Refine QI energy into HP. Useful when at bottleneck to strengthen your body.": "将气能量精炼为生命值。在瓶颈时很有用，可以增强你的身体。",
    "Realm": "境界",
    "Battle Manual": "战斗功法",
    "Proficiency:": "熟练度:",
    "Bloodline": "血脉",
    "Battle breakthrough bosses to advance to the next cultivation stage or realm.": "与突破boss战斗，进入下一个修炼阶段或境界",
    "Divine": "神圣",
    "HP": "生命值",
    "Increases final damage output.": "增加最终伤害输出。",
    "Increases Qi gained from cultivation.": "提升修炼获得的气。",
    "PALM": "掌",
    "palm": "掌",
    "Palm": "掌",
    "Palm Manual": "掌法",
    "Rebirth": "重生",
    "Rebirth (Requires Golden Core)": "重生（需要金丹期）",
    "Requires reaching QI bottleneck": "需要到达气的瓶颈",
    "Select Monster Tier": "选择怪物层级",
    "Talk to Secret Master": "与秘密大师对话",
    "Techniques": "技能",
    "Transcendental": "卓越",
    "Next Rebirth": "下一次重生",
    "Multiplier:": "乘数:",
    "Mythical": "神话",
    "Next Requirement": "下一个要求",
    "No technique equipped": "未装备技能",
    "Practice with your equipped weapon to increase proficiency.": "练习你装备的武器，以提高熟练度。",
    "Meditate and absorb celestial energy to increase your Qi and advance through realms.": "冥想和吸收天体能量来增加你的气，并提升境界。",
    "Learn from the Secret Master to improve technique drop rates.": "向秘密大师学习，提高技能掉落率。",
    "Converts potential QI gain into HP (2% base rate, scales with Battle Manual)": "将潜在的气增益转化为生命值（2%基础率，以战斗技能为准）",
    "Game saved successfully": "游戏保存成功！",
    "Stop": "停止",
    "Close": "关闭",
    "Cannot cultivate - you are in a bottleneck! Use Breakthrough to advance.": "不能继续修炼 — 你已达到瓶颈！使用突破来前进。",
    "Current Defense": "当前防御",
    "Level": "等级",
    "Next Defense": "下一级防御",
    "Not enough Spirit Stones": "灵石不足",
    "Rarity": "稀有度",
    "Refine": "精炼",
    "Refine Body Armor": "精炼身体护甲",
    "Refine Feet Armor": "精炼脚部护甲",
    "Refine Head Armor": "精炼头部护甲",
    "Success Chance": "成功几率",
    "Realm Bottleneck reached! Use Breakthrough action to advance to next realm.": "已达到当前境界瓶颈！使用突破动作进入下一个境界。",
    "Stop Combat": "停止战斗",
    "Combat stopped.": "战斗已停止。",
    "Attempting Breakthrough": "尝试突破",
    "Breakthrough Battle": "突破战斗",
    "Breakthrough successful! Reached FOUNDATION Realm": "突破成功! 到达 筑基 境界",
    "Cancel": "取消",
    "FOUNDATION": "筑基",
    "Your HP": "你的生命值",
    "No action selected. Game paused.": "没有选择任何动作。游戏已暂停。",
    "Fist Technique": "拳法技能",
    "Fist Technique activated": "拳法技能已激活",
    "Palm Technique": "掌法技能",
    "Palm Technique activated": "掌法技能已激活",
    "Activate": "激活",
    "ACTIVE": "活动",
    "Sell Technique": "出售技能",
    "INACTIVE": "未激活",
    "You obtained:": "你获得了:",
    "Sword Technique": "剑法技能",
    "Deactivate": "取消激活",
    "A common technique for fist.": "一个普通拳法技能.",
    "A uncommon technique for fist.": "一个罕见拳法技能.",
    "A rare technique for fist.": "一个稀有拳法技能.",
    "A common technique for palm.": "一个普通掌法技能.",
    "A uncommon technique for palm.": "一个罕见掌法技能.",
    "A rare technique for palm.": "一个稀有掌法技能.",
    "A common technique for sword.": "一个普通剑法技能.",
    "A uncommon technique for sword.": "一个罕见剑法技能.",
    "A rare technique for sword.": "一个稀有剑法技能.",
    "A common technique for spear.": "一个普通长矛技能.",
    "A uncommon technique for spear.": "一个罕见长矛技能.",
    "A rare technique for spear.": "一个稀有长矛技能.",
    "palm mastery advanced to UNCOMMON": "掌法精通达到了 罕见",
    "You died! Combat ended.": "你挂了! 战斗结束。",
    "You must have a spear equipped to use this technique": "你必须要有一个长矛装备才能使用这个技能",
    "You must have a fist equipped to use this technique": "你必须要有一个拳头装备才能使用这个技能",
    "You must have a palm equipped to use this technique": "你必须要有一个手掌装备才能使用这个技能",
    "You must have a sword equipped to use this technique": "你必须要有一个剑装备才能使用这个技能",
    "Palm Technique deactivated": "掌法技能已取消激活",
    "Spear Technique": "长矛技能",
    "GOLDEN CORE": "金丹期",
    "Breakthrough successful! Reached GOLDEN CORE Realm": "突破成功! 达到金丹期境界",
    "ORIGIN": "元婴",
    "Fist Mastery": "拳头精通",
    "Palm Mastery": "掌法精通",
    "Spear Mastery": "长矛精通",
    "Sword Mastery": "剑法精通",
    "Bloodline System Unlocked": "血脉系统已解锁",
    "Breakthrough successful! Reached ORIGIN Realm": "突破成功! 已达到 元婴 境界",
    "Cannot connect roots to each other": "不能把根节点彼此连接起来",
    "Critical Damage": "暴击伤害",
    "Critical Chance": "暴击几率",
    "Click on a node to connect to Bloodline...": "点击一个节点去连接到血脉...",
    "Added Critical Chance": "添加了暴击几率",
    "Added Critical Damage": "添加了暴击伤害",
    "Added Palm Mastery": "添加了掌法精通",
    "Added Fist Mastery": "添加了拳法精通",
    "Added Sword Mastery": "添加了剑法精通",
    "Added Spear Mastery": "添加了长矛精通",
    "Connected to Bloodline": "已连接到血脉",
    "Connection created": "连接已创建",
    "Click on another node to connect...": "点击另一个节点以连接...",
    "Click on the root first, then the node": "先点击根节点, 然后是其他节点",
    "Cannot connect node to itself": "不能连接到节点自身",
    "✓ Purchased": "✓ 已购买",
    "Tree validation failed": "树验证失败",
    "Node deleted": "节点已删除",
    "Cannot purchase this skill": "无法购买此技能",
    "Click to purchase": "点击购买",
    "Requirements not met": "未满足要求",
    "Palm Mastery, Fist Mastery": "掌法精通，拳法精通",
    "Tree applied! All points reset.": "树已应用！所有点数已重置。",
    "Not enough Spirit Stones": "灵石不足",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "/": "/",
    "⊙": "⊙",
    "⏸": "⏸",
    "▶": "▶",
    "▶▶": "▶▶",
    "▶▶▶": "▶▶▶",
    "⚡": "⚡",
    "⚡⚡": "⚡⚡",
    "⚡⚡⚡": "⚡⚡⚡",
    "⛶": "⛶",
    "💾": "💾",
    "🎁": "🎁",
    "🗑": "🗑",
    "📁": "📁",
    " /": " /",
    "!": "!",
    "×": "×",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如: Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头: "Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Damage: ": "伤害: ",
    "HP: ": "生命值: ",
    "Defense: +": "防御: +",
    "Power Level: ": "战力等级: ",
    "years": "年",
    "Action activated: ": "动作已激活: ",
    "Equipped: ": "已装备: ",
    "Monster defeated! ": "怪物已被击败！",
    "Common +": "普通 +",
    "Uncommon +": "罕见 +",
    "Rare +": "稀有 +",
    "Common ": "普通 ",
    "Uncommon ": "罕见 ",
    "Rare ": "稀有 ",
    "Weapon: ": "武器: ",
    "Rarity: ": "稀有度: ",
    "Equipped Common Palm Technique to slot ": "已装备 普通掌法技能 到槽位 ",
    "Equipped Uncommon Palm Technique to slot ": "已装备 罕见掌法技能 到槽位 ",
    "Equipped Rare Palm Technique to slot ": "已装备 稀有掌法技能 到槽位 ",
    "Equipped Common Fist Technique to slot ": "已装备 普通拳法技能 到槽位 ",
    "Equipped Uncommon Fist Technique to slot ": "已装备 罕见拳法技能 到槽位 ",
    "Equipped Rare Fist Technique to slot ": "已装备 稀有拳法技能 到槽位 ",
    "Body Armor upgraded to Common! Defense: ": "身体护甲已升级到普通! 防御: ",
    "Body Armor upgraded to Uncommon! Defense: ": "身体护甲已升级到罕见! 防御: ",
    "Body Armor upgraded to Rare! Defense: ": "身体护甲已升级到稀有! 防御: ",
    "Head Armor upgraded to Common! Defense: ": "头部护甲已升级到普通! 防御: ",
    "Head Armor upgraded to Uncommon! Defense: ": "头部护甲已升级到罕见! 防御: ",
    "Head Armor upgraded to Rare! Defense: ": "头部护甲已升级到稀有! 防御: ",
    "Feet Armor upgraded to Common! Defense: ": "脚部护甲已升级到普通! 防御: ",
    "Feet Armor upgraded to Uncommon! Defense: ": "脚部护甲已升级到罕见! 防御: ",
    "Feet Armor upgraded to Rare! Defense: ": "脚部护甲已升级到稀有! 防御: ",
    "Unequipped technique from slot ": "脱下技能从槽位 ",
    "Palm Mastery already has maximum connections": "掌法精通已经拥有了最大的连接",
    "Fist Mastery already has maximum connections": "拳法精通已经拥有了最大的连接",
    "Sword Mastery already has maximum connections": "剑法精通已经拥有了最大的连接",
    "Spear Mastery already has maximum connections": "长矛精通已经拥有了最大的连接",
    "Bloodline root already has maximum connections": "血脉根节点已经拥有了最大的连接",
    "Critical Damage already has maximum connections": "暴击伤害已经拥有了最大的连接",
    "Critical Chance already has maximum connections": "暴击几率已经拥有了最大的连接",
    "Purchased: ": "已购买: ",
    "Requires: ": "要求: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如: 13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾: " Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    '!': '!',
    "Common Palm Technique": "普通掌法技能",
    "Uncommon Palm Technique": "罕见掌法技能",
    "Rare Palm Technique": "稀有掌法技能",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^T([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\(([\d\.,]+)x\)$/,
    /^\+\(([\d\.,]+)\)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字: (\d+)
//字母加数字: ([\d\.]+[A-Za-z])
//逗号: ([\d\.,]+)
//小数点: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
//&nbsp;空格: \xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^New Bloodline Milestone! Tier (.+) conquered. (.+) Bloodline Point$/, '新血脉里程碑! 层级 $1 已征服. $2 血脉点数'],
    [/^Sold Common Sword Technique for (.+) Spirit Stones$/, '出售普通剑法技能获得了 $1 灵石'],
    [/^Sold Uncommon Sword Technique for (.+) Spirit Stones$/, '出售罕见剑法技能获得了 $1 灵石'],
    [/^Sold Rare Sword Technique for (.+) Spirit Stones$/, '出售稀有剑法技能获得了 $1 灵石'],
    [/^Sold Common Spear Technique for (.+) Spirit Stones$/, '出售普通长矛技能获得了 $1 灵石'],
    [/^Sold Uncommon Spear Technique for (.+) Spirit Stones$/, '出售罕见长矛技能获得了 $1 灵石'],
    [/^Sold Rare Spear Technique for (.+) Spirit Stones$/, '出售稀有长矛技能获得了 $1 灵石'],
    [/^Sold Common Fist Technique for (.+) Spirit Stones$/, '出售普通拳法技能获得了 $1 灵石'],
    [/^Sold Uncommon Fist Technique for (.+) Spirit Stones$/, '出售罕见拳法技能获得了 $1 灵石'],
    [/^Sold Rare Fist Technique for (.+) Spirit Stones$/, '出售稀有拳法技能获得了 $1 灵石'],
    [/^Sold Common Palm Technique for (.+) Spirit Stones$/, '出售普通掌法技能获得了 $1 灵石'],
    [/^Sold Uncommon Palm Technique for (.+) Spirit Stones$/, '出售罕见掌法技能获得了 $1 灵石'],
    [/^Sold Rare Palm Technique for (.+) Spirit Stones$/, '出售稀有掌法技能获得了 $1 灵石'],
    [/^Refinement FAILED! Lost (.+) Spirit Stones.$/, '精炼失败! 失去了 $1 灵石.'],
    [/^Feet Armor refined to (.+)! Defense: (.+)$/, '脚部护甲 精炼到 $1! 防御: $2'],
    [/^Head Armor refined to (.+)! Defense: (.+)$/, '头部护甲 精炼到 $1! 防御: $2'],
    [/^Body Armor refined to (.+)! Defense: (.+)$/, '身体护甲 精炼到 $1! 防御: $2'],
    [/^Finished early! Defeated (.+) bosses. Breakthrough successful! Realm stats bonus: (.+)$/, '提前完成! 击败了 $1 Boss. 突破成功! 境界属性加成: $2'],
    [/^Defeat Boss Tier (.+) to breakthrough! Each additional boss increases Realm Stats by (.+).$/, '击败 Boss层级 $1 以突破! 每个额外Boss提升境界属性 $2.'],
    [/^Defeated (.+) bosses! Breakthrough successful! Realm stats bonus: (.+)$/, '击败 $1 Boss! 突破成功! 境界属性加成: $2'],
    [/^Bosses Defeated: (.+) \| Realm Stats Bonus: (.+)$/, 'Boss已击败: $1 | 境界属性加成: $2'],
    [/^Boss Tier (.+) defeated! Tier (.+) defeated!$/, 'Boss层级 $1 已击败! 层级 $2 已击败!'],
    [/^Boss Tier (.+) defeated! (.+) to all realm stats! \(Total: (.+)\)$/, 'Boss层级 $1 已击败! $2 到所有境界属性! (总计: $3)'],
    [/^Combat started against Tier (.+) Monster!$/, '战斗已开始！对抗层级 $1 怪物！'],
    [/^Combat started against Boss Tier (.+)!$/, '战斗已开始！对抗Boss层级 $1！'],
    [/^Battle started against Boss Tier (.+)!$/, '战斗已开始！对抗Boss层级 $1！'],
    [/^Battle Manual upgraded to Tier (.+)!$/, '战斗技能功法升级到了层级 $1！'],
    [/^Cultivation Manual upgraded to Tier (.+)!$/, '修炼功法升级到了层级 $1！'],
    [/^Advanced to QI CONDENSATION Stage (.+)! \((.+) DMG, (.+) HP, (.+) DEF\)$/, '达到凝气阶段 $1!  ($2 伤害, $3 生命值, $4 防御)'],
    [/^Advanced to ORIGIN Stage (.+)! \((.+) DMG, (.+) HP, (.+) DEF\)$/, '达到元婴阶段 $1!  ($2 伤害, $3 生命值, $4 防御)'],
    [/^Advanced to FOUNDATION Stage (.+)! \((.+) DMG, (.+) HP, (.+) DEF\)$/, '达到筑基阶段 $1!  ($2 伤害, $3 生命值, $4 防御)'],
    [/^Advanced to GOLDEN CORE Stage (.+)! \((.+) DMG, (.+) HP, (.+) DEF\)$/, '达到金丹期阶段 $1!  ($2 伤害, $3 生命值, $4 防御)'],
    [/^Cost per day: (.+) QI \+ (.+) Spirit Stones$/, '每日成本: $1 气 + $2 灵石'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Spear Damage$/, '+$1% 长矛伤害'],
    [/^\+([\d\.]+)\% Palm Damage$/, '+$1% 手掌伤害'],
    [/^\+([\d\.]+)\% Sword Damage$/, '+$1% 剑法伤害'],
    [/^\+([\d\.]+)\% Fist Damage$/, '+$1% 拳头伤害'],
    [/^\+([\d\.]+)\% Critical Chance$/, '+$1% 暴击几率'],
    [/^\+([\d\.]+)\% Critical Damage$/, '+$1% 暴击伤害'],
    [/^\+([\d\.]+)\% fist mastery$/, '+$1% 拳头精通'],
    [/^\+([\d\.]+)\% palm mastery$/, '+$1% 手掌精通'],
    [/^\+([\d\.]+) Spirit Stones$/, '+$1 灵石'],
    [/^\+([\d\.]+) QI$/, '+$1 气'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Connector$/, '$1 连接器'],
    [/^([\d\.,]+) Connectors$/, '$1 连接器'],
    [/^([\d\.,]+)x Speed$/, '$1x 速度'],
    [/^Slot ([\d\.,]+)$/, '槽位 $1'],
    [/^Slot ([\d\.,]+): $/, '槽位 $1: '],
    [/^Equip Slot ([\d\.,]+)$/, '装备槽位 $1'],
    [/^Tier ([\d\.,]+) Monster$/, '层级 $1 怪物'],
    [/^Tier ([\d\.,]+) Monster 🔒$/, '层级 $1 怪物 🔒'],
    [/^Fighting Boss Tier ([\d\.,]+)$/, '对抗Boss层级 $1'],
    [/^Boss Tier ([\d\.,]+)$/, 'Boss层级 $1'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^Removed ([\d\.,]+) connection\(s\)!$/, '移除了 $1 连接!'],
    [/^\(Base: ([\d\.,]+), Tier: ([\d\.,]+)\)$/, '(基础: $1, 层级: $2)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^([\d\.,]+) \/ ([\d\.,]+) HP$/, '$1 \/ $2 生命值'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) \(All-time: (.+)\)$/, '$1 (所有时间: $2)'],
    [/^Sell Price: (.+) SS$/, '出售价格: $1 灵石'],
    [/^Reward: (.+) SS$/, '奖励: $1 灵石'],
    [/^Qi Cost: (.+)\/attack$/, '气成本: $1/攻击'],
    [/^Cost: (.+) Spirit Stones$/, '成本: $1 灵石'],
    [/^Cost: (.+) Points$/, '成本: $1 点数'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求: $1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);
